AllCops:
  NewCops: enable
  Exclude:
    - 'config/**/*'
  TargetRubyVersion: 3.4
  SuggestExtensions: false

Metrics/AbcSize:
  Max: 18
  Exclude:
    - 'cli.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Style/Documentation:
  Enabled: false

Metrics/CyclomaticComplexity:
  Exclude:
    - 'cli.rb'

Metrics/MethodLength:
  Exclude:
    - 'cli.rb'

Metrics/PerceivedComplexity:
  Exclude:
    - 'cli.rb'

Style/SafeNavigationChainLength:
  Exclude:
    - 'cli.rb'

Layout/LineLength:
    Exclude:
    - 'cli.rb'