AllCops:
  NewCops: enable
  Exclude:
    - 'config/**/*'
  TargetRubyVersion: 3.4
  SuggestExtensions: false

Metrics/AbcSize:
  Max: 18

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Style/Documentation:
  Enabled: false
