rules:
  - type: "BogoRule"
    product_code: "GR1"
  - type: "BulkDiscountRule"
    product_code: "SR1"
    min_quantity: 3
    new_price: 4.50
  - type: "TwoThirdsRule"
    product_code: "CF1"
    min_quantity: 3